[build]
  # Ця команда говорить Netlify, як збирати проєкт.
  # В нашому випадку нічого збирати не потрібно, тому команда може бути пустою.
  command = "npm install"

  # Це найважливіший рядок: вказуємо, де лежать наші файли для публікації.
  # Крапка "." означає, що вся папка проєкту є публічною.
  publish = "."

  # Прямо вказуємо Netlify, де знаходяться наші хмарні функції.
  functions = "netlify/functions/"

[functions]
  # Вказуємо, що для запуску функцій потрібен Node.js
  node_bundler = "esbuild"
